Feature: adjust branch name

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,7 +21,7 @@ env:
 jobs:
   linting:
     name: Linting
-    if: github.event_name == 'pull_request' && github.base_ref == 'main_core'
+    if: github.event_name == 'pull_request' && github.base_ref == 'main'
     runs-on: ubuntu-latest
 
     steps:
@@ -30,8 +30,8 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Fetch main_core branch history
-        run: git fetch origin main_core:refs/remotes/origin/main_core
+      - name: Fetch main branch history
+        run: git fetch origin main:refs/remotes/origin/main
 
       - name: Install Python Dependencies
         run: pip install -r requirements.txt
@@ -46,11 +46,11 @@ jobs:
         run: dbt parse
 
       - name: Run Pre-commit checks
-        run: pre-commit run --from-ref origin/main_core --to-ref HEAD --all-files
+        run: pre-commit run --from-ref origin/main --to-ref HEAD --all-files
 
   build:
     name: Build dbt Models
-    if: github.event_name == 'pull_request' && github.base_ref == 'main_core'
+    if: github.event_name == 'pull_request' && github.base_ref == 'main'
     runs-on: ubuntu-latest
     needs: linting
 
@@ -80,11 +80,11 @@ jobs:
       - name: Parse dbt project
         run: dbt parse
 
-      - name: Try to checkout manifest.json from main_core
+      - name: Try to checkout manifest.json from main
         run: |
-          git fetch origin main_core
+          git fetch origin main
           mkdir -p target-defer
-          git checkout origin/main_core -- target-defer/manifest.json || echo "manifest.json not found on main_core, proceeding without deferral."
+          git checkout origin/main -- target-defer/manifest.json || echo "manifest.json not found on main, proceeding without deferral."
 
       - name: Build dbt models
         run: |
@@ -112,7 +112,7 @@ jobs:
 
   upload_manifest:
     name: Upload Manifest
-    if: github.ref == 'refs/heads/main_core' && github.event_name == 'push'
+    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
     runs-on: ubuntu-latest
 
     steps:
@@ -153,12 +153,12 @@ jobs:
         run: |
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git config --global user.name "GitHub Actions CI"
-          git checkout main_core
-          git pull origin main_core
+          git checkout main
+          git pull origin main
           git add target-defer/manifest.json
           if git diff --staged --quiet; then
             echo "No changes to manifest.json to commit."
           else
             git commit -m "chore: Upload manifest.json from CI [skip ci]"
-            echo "Pushing updated manifest.json to main_core..."
-            git push origin main_core
+            echo "Pushing updated manifest.json to main..."
+            git push origin main
